### PR TITLE
Grow stack and heap on access if necessary

### PR DESCRIPTION
**Pull request by tyilo**

### CODE REVIEW

**Comment by tyilo** [comment]
Actually it might be better to just return 0's instead of growing the stack/heap on access.

**Comment by orlp** [comment]
I'd rather not do this, as it makes debugging harder. I think it's better that reading uninitialized memory is an error rather than secretly giving back zeroes.

**Comment by tyilo** [comment]
But then this should also be an error:

```
sw 0x10000, 1
lw a, 0x5000
```

**Comment by orlp** [comment]
I've decided that the _GOLF_ CPU's memory will be all zeros at program startup.

**Comment by tyilo** [comment]
Thanks, however it doesn't always work.

Running:

```
    sw 0, -1
    lw a, 1
    halt 0
```

throws the exception:

```
Traceback (most recent call last):
  File "/Users/Tyilo/repos/golf-cpu/assemble.py", line 373, in <module>
    sys.exit(golf.GolfCPU(binary).run())
  File "/Users/Tyilo/repos/golf-cpu/golf.py", line 203, in run
    self.execute_instr(instr_name, instr_args)
  File "/Users/Tyilo/repos/golf-cpu/golf.py", line 155, in execute_instr
    elif instr == "lw":   self.regs[args[0]] = self.load(args[1], 8)
  File "/Users/Tyilo/repos/golf-cpu/golf.py", line 89, in load
    return struct.unpack("<" + fmts[width], bytes(r + [0] * width))[0]
struct.error: unpack requires a bytes object of length 8
```

**Comment by orlp** [comment]
@Tyilo Sorry about that, fixed.

**Comment by tyilo** [comment]
Thanks!

**Pull request closed without merging**
